# Generated by Django 5.2.10 on 2026-01-17 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('регистрация', 'Регистрация пассажиров'), ('досмотр', 'Предполетный досмотр'), ('багаж', 'Багажная служба'), ('информация', 'Информационная стойка'), ('посадка', 'Посадка на рейс'), ('грузовой терминал', 'Грузовой терминал'), ('медпункт', 'Медпункт аэропорта'), ('vip-зал', 'VIP-зал'), ('транспорт', 'Наземный транспорт'), ('авиакасса', 'Авиакасса')], max_length=50)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField(help_text='Стаж работы в годах')),
                ('office_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник аэропорта',
                'verbose_name_plural': 'Сотрудники аэропорта',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('office_number', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('запланирован', 'Запланирован'), ('завершен', 'Завершен'), ('отменен', 'Отменен'), ('пассажир не явился', 'Пассажир не явился')], default='запланирован', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='airport_app.doctor')),
            ],
            options={
                'verbose_name': 'Заявка пассажира',
                'verbose_name_plural': 'Заявки пассажиров',
                'ordering': ['-appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('insurance_number', models.CharField(max_length=20, unique=True)),
                ('attached_to_clinic', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('prescription', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='airport_app.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='airport_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='airport_app.patient')),
            ],
            options={
                'verbose_name': 'Служебная запись',
                'verbose_name_plural': 'Служебные записи',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='airport_app.patient'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (0, 'Воскресенье')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('office_number', models.CharField(max_length=10)),
                ('is_working', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='airport_app.doctor')),
            ],
            options={
                'verbose_name': 'Расписание смены',
                'verbose_name_plural': 'Расписания смен',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='airport_app.schedule'),
        ),
    ]
